lib/mongo/collection.extension.js

Documents should not be transformed (performance), if global transforming was activated for a collection.

explicitly remove global transforms in update and remove

---

lib/cache/ObservableCollection.js
lib/cache/PublicationEntry.js

We’re finally about to use redis-oplog in production @ TeamGrid 🎉🎉🎉
I’ve found some issues while testing it with our app.
**check fieldsArray instead of options.fields**
I had strange issues while checking options.fields. It looked like
options.fields got changed after the cursor was initialized.
options.fields was an empty object but the fieldsArray was undefined.
Since there is only a check if options.fields is defined, the result
was an exception, that fieldsArray is undefined.
**check if current invocation has a connection**
I have some cases where the connection is null. I think it has
something todo with server side method calls
(https://github.com/meteor/meteor/blob/84ed04b8f3b99cf16b5540f2e0193d47e
4f8ccf6/packages/ddp-server/livedata_server.js#L1631-L1647)

Fix fields and ddp connection checks

---

lib/mongo/extendObserveChanges.js

In my app, I'm seeing this error on startup:
```
TypeError: Cannot read property 'get' of undefined
at getObserverConnection (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:114:34)
at createObserve (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:57:21)
at [object Object].Object.assign.observe (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:25:51)
at <...stack trace in my app...>
```
To fix this, I've added more defensive handling for the case where `DDP._CurrentPublicationInvocation` is undefined.

More defensive handling of DDP._CurrentPublicationInvocation

---

lib/processors/direct.js

It's valid to publish a record by ID before that record exists. Here's a (very contrived) example that works with vanilla Meteor, but causes and error and incorrect behavior with redis-oplog:
```
Foo = new Mongo.Collection('Foo')
Meteor.publish('newfoo', function() {
newid = Random.id();
Meteor.setTimeout(() => {
Foo.insert({ _id: newid })
}, 500)
return Foo.find({ _id: newid });
})
```
I'm hitting this in my app because I'm using a publishComposite-style technique to publish a parent record that has a list of child IDs, as well as those child records. This works if I insert the child before updating the parent, but it's a lot easier for me to to it the other way around (update the parent, then insert the child) because I have some collection hooks that synchronize the child record to an …

Add insert handler for direct processor

---

lib/config.js
lib/mongo/lib/dispatchers.js

Add a new option, `externalRedisPublisher`, that can be used if there is an external system that's responsible for writing changes to Redis. It works like `pushToRedis: false`, except that it still handles optimistic UI.

Add externalRedisPublisher option

---

lib/cache/lib/getChannels.js
lib/config.js
lib/mongo/lib/compensateForLatency.js
lib/mongo/lib/publish.js
lib/redis/RedisSubscriber.js
lib/utils/getChannelName.js

node-redis does not apply the prefix to channel names (they're [only applied to keys](https://github.com/NodeRedis/node_redis/blob/79558c524ff783000a6027fb159739770f98b10e/index.js#L934), and [getKeyIndexes](https://github.com/NodeRedis/redis-commands/blob/master/index.js#L66) doesn't treat [channel names as keys](https://github.com/NodeRedis/redis-commands/blob/master/commands.json#L1017)).
This patch applies the Redis prefix to the channel names used by redis-oplog.

Use redis prefix for channels

---

lib/mongo/Mutator.js
lib/mongo/lib/getMutationConfig.js

This PR makes two changes to allow us to more frequently use the original insert/update/delete methods when a user is using an external publisher:
1) Use the original methods any time we're using an external redis publisher AND we don't need optimistic UI processing
2) Default to disabling optimistic UI processing if we're not inside a method.
This means that when using an external publisher (so we don't need to do any work to figure out what changes to publish to Redis), we can always use the original methods for things that aren't part of a Meteor method, and users can easily have us always use the original methods by disabling optimistic UI processing.

Maximize use of original methods when using an external publisher

---

lib/cache/PublicationEntry.js
lib/mongo/lib/dispatchers.js
lib/redis/RedisSubscriber.js

This PR does two things:
- Add a bindEnvironment when dispatching events in `dispatcher.js` so that `DDP._CurrentInvocation.get();` in PublicationEntry.js works -- I think we were always hitting the second branch and running all observers synchronously.
- When using an external redis publisher, don't process local observers other than those that are strictly required for optimistic UI. External publishers won't be able to take advantage of the optimization from https://github.com/cult-of-coders/redis-oplog/pull/260 -- they'll always re-process events from Redis -- so we can at least make the initial optimistic pass as minimal as possible (every else will get updated when the write notification comes in from Redis)

Avoid double-dispatch of changes as much as possible when using external publisher

---

docs/vent.md

Fixed a typo and also updated the documentation to note that if your message your delivering via a Vent publish is an actual Number value that can reach zero or is a Boolean value, you'll need to wrap it in an object.
The documentation wasn't clear to me that you had to pass the message as an object because your example uses a status example that is an actual value and not an object.

Updated Vent Publish Function Comments

---

lib/mongo/lib/dispatchers.js
lib/redis/RedisSubscriber.js
lib/utils/getDedicatedChannel.js

Not really a bug, but just cleans up the naming of dedicated channels.
Old version: `collection::ObjectId(xyz)`
New version: `collection::xyz`

update dedicated channel name for Mongo.ObjectID's

---

lib/cache/PublicationEntry.js

I had added an optimization that caused redis-oplog to only send the updates that were necessary for optimistic UI when using `externalRedisPublisher`, because we'll have to re-process the changes anyway when we get the notification from Redis (because when we're using an external redis publisher, we can't track which updates we have and haven't dealt with).
Unfortunately, this optimization was incorrect -- because we only send updates if our cache indicates a change actually occurred, this optimization caused us to not send updates to other clients on the server that accepted the change.
What would happen is:
1) The server would accept the change and write to Mongo
2) It would send out the updates needed for optimistic UI changes, and skip sending other updates
3) It would receive a …

Roll back invalid optimization for externalRedisPublisher

---

lib/cache/mongoIdMap.js
lib/processors/testing/limit-sort.test.js
package.js

Change the implementation of `MongoIDMap`, to remove usage of private
fields (`_map`). This should prevent breakage if the implementation of
`IdMap` were to change.
Additionally, change the internal data structure from an `Object` to a `Map`.
---
@theodorDiaconu Getting this patched now, as I'm hoping to get some breaking changes to `id-map` upstreamed.

Remove usage of meteor/id-map

---

lib/redis/lib/getFieldsOfInterestFromAll.js
lib/redis/testing/getFieldsOfInterestFromAll.js

Redis oplog does some work to minimize the fields projection given for a mongo query. If we encounter a situation in which fields of interest has two fields `master.slave.field`, and `slave`, the function `removeChildrenOfParents` is currently omitting `master.slave.field` because it sees that `slave.` is already in the list of returned fields. This was causing observes to be called with documents not containing all necessary fields in the Qualia application.
To fix, we say we have only found a parent field if another field starts with the current field, rather than includes it.

only remove children from fields projection if their parent is top-level

---

lib/mongo/Mutator.js

Calling `collection.upsert()` usually returns an object, containing `numberAffected` and an optional `insertedId` which contains the id of the document created if no document was found to update.
When installing this package, the object returned will always contain both properties, `insertedId` being `undefined` if a document was found.
In my code, I checked - not for the value - but for the absence of the property, which got some of my logic to fail after installing this package.
I couldn't find any tests for this file - are the modifications tested to return the exact same result as Meteor would initially?

After installing this package, an upsert always returns property `insertedId`

---

lib/mongo/Mutator.js

Can be reproduced by initializing this plugin and using an empty selector in a remove command:
```js
const collection = new Mongo.Collection('dummy');
collection.remove();
```

Fixed crash on remove if selector was undefined

---

lib/mongo/Mutator.js

Can be reproduced by initializing this plugin and using a callback in the remove command to retrieve the number of removed documents:
```js
const collection = new Mongo.Collection('dummy');
collection.remove({}, function (error, count) {
console.log(count); // is always undefined
});
```

Added the count of deleted items to the `remove` callback

---

lib/mongo/Mutator.js

As in #314, I don't know if or how I should set up a test-environment for this use-case, but these are vital. They ensure that all the arguments are given to the underlying meteor method.

Fix to call collection callbacks if externalRedisPublisher is enabled

---

.npm/package/npm-shrinkwrap.json
.travis.yml
CONTRIBUTING.md
lib/cache/testing/filterFieldsForFetching.test.js
lib/processors/testing/getStrategy.test.js
lib/processors/testing/synthetic.test.js
lib/redis/testing/getFieldsOfInterestFromAll.js
lib/utils/testing/extractIdsFromSelector.test.js
lib/utils/testing/getFields.test.js
package.js
testing/accounts/client.js
testing/client_side_mutators.js
testing/collection-defaults/client.js
testing/collection_hooks.server.js
testing/collection_transform.js
testing/custom-publications/client.js
testing/include_prev_doc.js
testing/initial_add.js
testing/main.client.js
testing/object-id/client.js
testing/observe_callbacks.server.js
testing/optimistic-ui/client.test.js
testing/polling/client.js
testing/publish-counts/client.js
testing/publishComposite/client.test.js
testing/server-autorun/client.js
testing/synthetic_mutators.js
testing/transformations/client.js
testing/transformations/server.js
testing/vent/client.js

Includes all changes of #316, adds one missing import-statement.
In addition I tried to switch the selenium based chrome test-driver over to puppeteer, which does not require root access or an installation of google chrome.

Use chai by npm and replace chrome by puppeteer

---

lib/cache/testing/filterFieldsForFetching.test.js
lib/processors/testing/getStrategy.test.js
lib/processors/testing/synthetic.test.js
lib/redis/testing/getFieldsOfInterestFromAll.js
lib/utils/testing/extractIdsFromSelector.test.js
lib/utils/testing/getFields.test.js
package.js
testing/accounts/client.js
testing/client_side_mutators.js
testing/collection-defaults/client.js
testing/collection_hooks.server.js
testing/collection_transform.js
testing/custom-publications/client.js
testing/initial_add.js
testing/main.client.js
testing/object-id/client.js
testing/observe_callbacks.server.js
testing/optimistic-ui/client.test.js
testing/polling/client.js
testing/publish-counts/client.js
testing/publishComposite/client.test.js
testing/server-autorun/client.js
testing/synthetic_mutators.js
testing/transformations/client.js
testing/transformations/server.js
testing/vent/client.js

The `practicalmeteor:chai` package prevents us from updating to 2.0.0. This replaces it with the regular `chai` package

Replace practicalmeteor:chai with chai

---

docs/how_it_works.md

Simply added the `js` tag to code blocks in the markdown guide so they are colored and easier to read.

Add color to code blocks in "How it Works" guide

---

README.md

I noticed that an URL that was supposed to lead to details about Redis' configuration wasn't working as I expected it to, so I updated it.

Fix URL to Redis configuration documentation

---

lib/cache/ObservableCollection.js

When used in Meteor 3.1, redis-oplog causes crashes because the Meteor "users" collection is not found when calling `Mongo.Collection.__getCollectionByName()`.
This PR fixes it by using the more recent `Meteor.getCollection()` introduced in Meteor 3.0.2

Fix issue with Mongo.Collection.__getCollectionByName not resolving 'users' when used in Meteor 3.1
